// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKYpviLuXmDEXcU8jlBDst5Uh8BjVpak',
    appId: '1:580907471269:android:a6eab9b91c81113d99584c',
    messagingSenderId: '580907471269',
    projectId: 'mis-seminarska-stockanalyzer',
    storageBucket: 'mis-seminarska-stockanalyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_gB1MNw77kHC32svjg8qMJbnsCjzGO0',
    appId: '1:580907471269:ios:7192adba54211ab599584c',
    messagingSenderId: '580907471269',
    projectId: 'mis-seminarska-stockanalyzer',
    storageBucket: 'mis-seminarska-stockanalyzer.firebasestorage.app',
    iosBundleId: 'com.example.domashniProekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSqNimrqUoS_Jifi-2nZWvgCyDtss6mtI',
    appId: '1:580907471269:web:2b7aa9f161fceb9f99584c',
    messagingSenderId: '580907471269',
    projectId: 'mis-seminarska-stockanalyzer',
    authDomain: 'mis-seminarska-stockanalyzer.firebaseapp.com',
    storageBucket: 'mis-seminarska-stockanalyzer.firebasestorage.app',
  );
}
